import manifest from "@/lib/images/manifest.json";

// Serves the WebP variants generated by scripts/optimize-images.mjs (src-<width>.webp) with
// intrinsic width/height so the browser reserves space (no layout shift). Paths without a
// manifest entry (e.g. files uploaded later through the admin panel) render as a plain <img>.
export default function ResponsiveImage({ src, alt = "", sizes = "100vw", priority = false, eager = false, className, style }) {
	const meta = manifest[src];
	const common = {
		alt,
		className,
		style,
		decoding: "async",
		loading: priority || eager ? "eager" : "lazy",
		...(priority ? { fetchpriority: "high" } : {}),
		...(meta ? { width: meta.w, height: meta.h } : {}),
	};

	if (!meta?.widths?.length) {
		return <img src={src} {...common} />;
	}

	const base = src.replace(/\.(png|jpe?g|webp)$/i, "");
	const srcSet = meta.widths.map((w) => `${base}-${w}.webp ${w}w`).join(", ");
	const fallback = `${base}-${meta.widths[meta.widths.length - 1]}.webp`;
	return <img src={fallback} srcSet={srcSet} sizes={sizes} {...common} />;
}
