"""Build a Font Awesome subset for the icons the site actually uses.

Scans components/app/lib and the CMS data files for `fa-*` icon names, then writes:
  - public/fonts/fa/fa-solid-900.woff2, fa-brands-400.woff2  (glyph subsets)
  - app/fa-subset.css                                        (base FA rules + used icon rules)
  - lib/icons/fa-subset.json                                 (icon names + versioned solid font URL)

Icons chosen later in the admin panel that are not in the subset are handled at runtime by
components/common/IconFallback.jsx, which loads the full Font Awesome stylesheet on demand.

Usage (from sofax/):  python3 scripts/build-icon-subset.py   (needs: pip install fonttools brotli)
"""
import glob
import hashlib
import json
import os
import re

from fontTools import subset

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FA = os.path.join(ROOT, "node_modules/@fortawesome/fontawesome-free")
SOURCES = [
    "components/**/*.js*",
    "app/**/*.js*",
    "lib/**/*.js*",
    "lib/**/*.json",
    "public/data/*.json",
    "../data/*.json",
]
# Template folders that no route renders anymore.
SKIP = re.compile(r"components/home/home-(?!five|one)")


def used_icon_names():
    names = set()
    for pattern in SOURCES:
        for path in glob.glob(os.path.join(ROOT, pattern), recursive=True):
            if SKIP.search(path.replace(os.sep, "/")):
                continue
            text = open(path, encoding="utf-8", errors="ignore").read()
            names.update(re.findall(r"\bfa-([a-z0-9]+(?:-[a-z0-9]+)*)", text))
    return names


def split_rules(css):
    """Top-level rules of minified CSS; at-rule blocks (@media, @keyframes, @font-face) stay whole."""
    rules, depth, start = [], 0, 0
    for i, ch in enumerate(css):
        if ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                rules.append(css[start : i + 1])
                start = i + 1
    return rules


ICON_SELECTOR = re.compile(r"^\.fa-([a-z0-9-]+):(?:before|after)$")


def main():
    used = used_icon_names()
    css = open(os.path.join(FA, "css/all.min.css"), encoding="utf-8").read()
    css = re.sub(r"/\*.*?\*/", "", css, flags=re.S)
    kept, codepoints, icons = [], set(), set()
    font_faces = {}
    for rule in split_rules(css):
        head, body = rule.split("{", 1)
        if head.startswith("@font-face"):
            family = re.search(r'font-family:"([^"]+)"', body).group(1)
            weight = re.search(r"font-weight:(\d+)", body)
            if family == "Font Awesome 6 Brands":
                font_faces["fa-brands-400"] = len(kept)
                kept.append(("Font Awesome 6 Brands", 400, "fa-brands-400"))
            elif family == "Font Awesome 6 Free" and weight and weight.group(1) == "900":
                font_faces["fa-solid-900"] = len(kept)
                kept.append(("Font Awesome 6 Free", 900, "fa-solid-900"))
            continue  # regular + v4 compatibility faces are not used
        selectors = head.split(",")
        matches = [ICON_SELECTOR.match(sel) for sel in selectors]
        if all(matches):
            keep = [sel for sel, m in zip(selectors, matches) if m.group(1) in used]
            if not keep:
                continue
            icons.update(ICON_SELECTOR.match(sel).group(1) for sel in keep)
            for code in re.findall(r'content:"\\([0-9a-f]+)"', body):
                codepoints.add(int(code, 16))
            kept.append(",".join(keep) + "{" + body)
        else:
            kept.append(rule)

    os.makedirs(os.path.join(ROOT, "public/fonts/fa"), exist_ok=True)
    urls = {}
    for name in ("fa-solid-900", "fa-brands-400"):
        options = subset.Options()
        options.flavor = "woff2"
        options.layout_features = []
        options.notdef_outline = True
        font = subset.load_font(os.path.join(FA, f"webfonts/{name}.woff2"), options)
        subsetter = subset.Subsetter(options)
        subsetter.populate(unicodes=sorted(codepoints))
        subsetter.subset(font)
        target = os.path.join(ROOT, f"public/fonts/fa/{name}.woff2")
        subset.save_font(font, target, options)
        version = hashlib.md5(open(target, "rb").read()).hexdigest()[:10]
        urls[name] = f"/fonts/fa/{name}.woff2?v={version}"
        family, weight, _ = kept[font_faces[name]]
        kept[font_faces[name]] = (
            f'@font-face{{font-family:"{family}";font-style:normal;font-weight:{weight};font-display:swap;'
            f'src:url({urls[name]}) format("woff2")}}'
        )

    header = "/* Generated by scripts/build-icon-subset.py from Font Awesome Free 6.4.0 (https://fontawesome.com/license/free). Do not edit. */\n"
    open(os.path.join(ROOT, "app/fa-subset.css"), "w", encoding="utf-8").write(header + "".join(kept) + "\n")
    os.makedirs(os.path.join(ROOT, "lib/icons"), exist_ok=True)
    json.dump({"solidFont": urls["fa-solid-900"], "icons": sorted(icons)}, open(os.path.join(ROOT, "lib/icons/fa-subset.json"), "w"), indent=0)
    print(f"{len(icons)} icons, {len(codepoints)} glyphs")


if __name__ == "__main__":
    main()
