// Runs after `next build` (static export):
// 1. The app has a single root layout, so every exported page starts as <html lang="tr">;
//    set the real language on the locale-prefixed pages.
// 2. Write a one-year cache rule for the content-hashed files in _next/static.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const OUT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../out");
const LOCALES = ["en", "ru", "uz", "tk"];

function htmlFiles(dir, out = []) {
	for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
		const full = path.join(dir, entry.name);
		if (entry.isDirectory()) htmlFiles(full, out);
		else if (entry.name.endsWith(".html")) out.push(full);
	}
	return out;
}

let changed = 0;
for (const locale of LOCALES) {
	const dir = path.join(OUT, locale);
	if (!fs.existsSync(dir)) continue;
	for (const file of htmlFiles(dir)) {
		const html = fs.readFileSync(file, "utf8");
		const next = html.replace('<html lang="tr"', `<html lang="${locale}"`);
		if (next !== html) {
			fs.writeFileSync(file, next);
			changed += 1;
		}
	}
}
console.log(`postbuild: lang set on ${changed} pages`);

const STATIC_HTACCESS = `# Generated by scripts/postbuild.mjs: file names are content-hashed, so they never change.
<IfModule mod_headers.c>
    Header set Cache-Control "public, max-age=31536000, immutable"
</IfModule>
`;
fs.writeFileSync(path.join(OUT, "_next/static/.htaccess"), STATIC_HTACCESS);
console.log("postbuild: wrote _next/static/.htaccess");
