import localFont from "next/font/local";

// Subsets are generated by scripts/subset-fonts.py; keep the unicode-range values below in sync
// with it (next/font only accepts literal values here).

// Headings. No Arial fallback face here: it would swallow Cyrillic headings before they reach Inter.
export const clashGrotesk = localFont({
	src: "./fonts/clash-grotesk/ClashGroteskSemibold.woff2",
	display: "swap",
	variable: "--font-clash-grotesk",
	adjustFontFallback: false,
});

export const inter = localFont({
	src: [
		{ path: "./fonts/inter/subset/Inter-Regular.latin.woff2", weight: "400", style: "normal" },
		{ path: "./fonts/inter/subset/Inter-Medium.latin.woff2", weight: "500", style: "normal" },
		{ path: "./fonts/inter/subset/Inter-SemiBold.latin.woff2", weight: "600", style: "normal" },
		{ path: "./fonts/inter/subset/Inter-Bold.latin.woff2", weight: "700", style: "normal" },
	],
	display: "swap",
	variable: "--font-inter",
	declarations: [{ prop: "unicode-range", value: "U+0000-024F, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070-209F, U+20A0-20CF, U+2100-214F, U+2190-21FF, U+2212, U+2215, U+FEFF, U+FFFD" }],
});

// Only downloaded when a page contains Cyrillic text (Russian pages).
export const interCyrillic = localFont({
	src: [
		{ path: "./fonts/inter/subset/Inter-Regular.cyrillic.woff2", weight: "400", style: "normal" },
		{ path: "./fonts/inter/subset/Inter-Medium.cyrillic.woff2", weight: "500", style: "normal" },
		{ path: "./fonts/inter/subset/Inter-SemiBold.cyrillic.woff2", weight: "600", style: "normal" },
		{ path: "./fonts/inter/subset/Inter-Bold.cyrillic.woff2", weight: "700", style: "normal" },
	],
	display: "swap",
	variable: "--font-inter-cyrillic",
	preload: false,
	adjustFontFallback: false,
	declarations: [{ prop: "unicode-range", value: "U+0400-052F, U+2116" }],
});
